# Generated by Django 4.2.4 on 2023-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supplements/images'),
        ),
    ]
