# Generated by Django 4.2.4 on 2023-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_supplement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
